name: .NET Build

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- name: Setup .NET
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 3.1.x
    #- name: Restore dependencies
    #  run: dotnet restore ./src/EdFi.AnalyticsMiddleTier.Console/EdFi.AnalyticsMiddleTier.Console.csproj
    #- name: Build
    #  run: dotnet build ./src/EdFi.AnalyticsMiddleTier.Console/EdFi.AnalyticsMiddleTier.Console.csproj --configuration Release --no-restore
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    - name: build
      run: .\build.ps1 build -Configuration release -Version "1" -BuildCounter 1
